environment:
  matrix:
    - nodejs_version: 7

version: "{build}"
build: off
deploy: off

branches:
    only:
      - master

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - npm --version
  - cmd: "yarn run build"
